eureka:
    instance:
          preferIpAddress: false

spring:
    cloud:
        stream:
            bindings:
                sleuth:
                    destination: sleuth-stage
    datasource:
#        schema: classpath:/sql/init.sql
        url: jdbc:mysql://172.25.5.59:3306/zipkin?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: snake_rw
        password: snake_pwd
        continueOnError: true
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 3
        max-active: 20
        min-idle: 5
logging:
    config: classpath:logback-stage.xml
